console.log("Merge conflict")

func = () => {
    return 5+10
}

console.log(func())
